### PR TITLE
Fix Sidebar transitions and add the List component

### PR DESCRIPTION
**Pull request by GuillaumeAmat**
Classic `<Transition>` were not optimized (in a browser render way) and prevent to fully animate the close animation with React Router.

I had to dig deep to figure this out... :(

### CODE REVIEW

**Comment by bleucitron** [comment]
Currently, the `<Sidebar>` animates correctly in the storybook.

Do you mean that the `<Transition>` animation along with React Router makes `<Sidebar>` to not animate correctly ?

I used it in other places (`<Modal>`, `<Notification>`, `<Toolbar>`...), and we might need to check whether these components are impacted too (I'm thinking `<Modal>` might be).

**Comment by GuillaumeAmat** [comment]
Yep, yesterday I fought with React Router and React Transition Group... The main issue was that the MapContrib Next `Sidebar` opened by routes were not animated at the close step.

I dug for hours after documentations, issues, feedback on that subject and I finally got my answers:

* The React Transition Group documentation is bullshit/void/incomplete
* `Transition` is not a component meant to be used. It is the low level component
* Hence, `Transition` does not optimised the CSS transitions, and specifically the `transform` ones
* The `appear` step cannot be transitionned right now but it is not a big deal. It is likely the good approach on a second thought IMHO
* React Router offer three props to associate a component to a route: `render`, `children` and `component`
* The `render` prop cannot be used to handle the close transitions
* The `component` prop cannot manage props to the given component
* It only lets `children` to do the work, but... With that prop, the component is always rendered, even if the route does not match...
* So I had to adapt the sidebars behaviors and test if `props.match !== null` (when the route does not match obviously)

Sorry for the short descriptions, I was tired and pissed off at 4 am ^^

And yeah, we will have to do the same thing on the other components. I think they are all impacted, but maybe we should wait to see if that approach has some unexpected behaviors.

**Comment by GuillaumeAmat** [comment]
@iOiurson I added a new `List` component to that PR. It's not really related but I need to go fast on the developments... :/

**Review by bleucitron — APPROVED** [review]

**Comment by bleucitron** [comment]
Let's go fast then !

**Comment by GuillaumeAmat** [comment]
Thanks @iOiurson :)

**Pull request merged**
